# Site settings
title: Nehzilrz
author: 平芜泫
header-img: img/home-bg.jpg
email: me@patpat.net
description: "没了"
baseurl: ""
url: "http://nehzilrz.github.io"

github_username: nehzilrz
# twitter_username: SBootstrap
# facebook_username:  IronSummitMedia
# zhihu_username: ipwx
# weibo_username: korepwx

# Specify the navigation items by hand
navigation:
  -
    title: 分类
    url: /categories/
  -
    title: 标签云
    url: /tags/
  -
    title: 关于我
    url: /about/

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["footnotes", "tables", "with_toc_data", "no_intra_emphasis", "strikethrough", "superscript"]

highlighter: pygments
permalink: /:year/:month/:title/
paginate: 5
exclude: ["tools","less","node_modules","Gruntfile.js","package.json","README.md"]
excerpt_separator: <!--more-->
use_katex: true

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

# kramdown:
#   input: GFM